//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Experience
    {
        public string IDExperiencia { get; set; }
        public string C0_2_years { get; set; }
        public string C2_4_years { get; set; }
        public string C4_6_years { get; set; }
        public string C6_8_years { get; set; }
        public string C8_10_years { get; set; }
        public string C_10_years { get; set; }
    }
}
