//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto
{
    using System;
    using System.Collections.Generic;
    
    public partial class Qualifications
    {
        public string IDTitulacion { get; set; }
        public string University_Degree { get; set; }
        public string College_Diploma { get; set; }
        public string Graduate_Certificate { get; set; }
        public string Master_Degree { get; set; }
        public string Apprenticeship_Certificate { get; set; }
        public string Traineeship_Degree { get; set; }
        public string Bachelor_Degree { get; set; }
    }
}
